name: create-artifact
on: [push]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker run -v "$PWD:/src" batonogov/pyinstaller-windows "python setup.py install; pyinstaller -F --noupx youtube-upload.spec"
      - uses: actions/upload-artifact@v2
        with:
          name: youtube-upload.exe
          path: dist/youtube-upload.exe
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/youtube-upload.exe
          asset_name: youtube-upload.exe
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is the latest release"
      - run: docker run -v "$PWD:/src" batonogov/pyinstaller-linux "python setup.py install; pyinstaller -F --noupx youtube-upload.spec"
      - uses: actions/upload-artifact@v2
        with:
          name: youtube-upload
          path: dist/youtube-upload
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/youtube-upload
          asset_name: youtube-upload
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is the latest release"

